nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['http://localhost:8083']  # L'origine autorisée
        allow_headers: ['Content-Type', 'Authorization']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE']
        max_age: 3600
    paths:
        '^/api/':  # Chemin des routes API
            allow_origin: ['http://localhost:8083']  # Autoriser l'origine du frontend
            allow_headers: ['Content-Type', 'Authorization']
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE']
            allow_credentials: true
