spring.application.name=Crypto
spring.datasource.url=jdbc:postgresql://localhost:5432/crypto
spring.datasource.username=postgres
spring.datasource.password=itu16
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.mode=always

spring.profiles.active=dev
logging.level.org.springframework.boot.devtools=DEBUG


server.port=8088

spring.devtools.restart.include=**
spring.devtools.restart.exclude=**

firebase.config.path=src\main\resources\serviceAccountKey.json

