spring.application.name=Crypto
spring.datasource.url=jdbc:postgresql://localhost:5432/Crypto
spring.datasource.username=postgres
spring.datasource.password=itu16
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.mode=always
firebase.config.path=src\\main\\resources\\serviceAccountKey.json
